apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dapp-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dapp-frontend         # 這裡對應你的 Deployment 名稱
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50   # 超過 50% CPU 就會擴容

